(ns block-cljs.tutorials-a)

(def vect
  [
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <block type=\"text\" id=\"gBI#}|?X*;0m;I^ihQsC\" x=\"17\" y=\"33\">\n    <field name=\"dertext\">Hello, World!</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <block type=\"text\" id=\"NI)yg;:O!Z;@LWv@#x*b\" x=\"14\" y=\"16\">\n    <field name=\"dertext\">Hello, World!</field>\n  </block>\n  <block type=\"text\" id=\"1Nsm}F$u5ljQ@){,w/Pf\" x=\"16\" y=\"60\">\n    <field name=\"dertext\">I feel great.</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"(7gC*OGG$yxES*=1!Kgd\">println</variable>\n  </variables>\n  <block type=\"funs-h-2-cus\" id=\"3jlNw04eWrV5Facrs8]f\" x=\"11\" y=\"11\">\n    <field name=\"kopf\" id=\"(7gC*OGG$yxES*=1!Kgd\">println</field>\n    <value name=\"args-2\">\n      <block type=\"text\" id=\"NI)yg;:O!Z;@LWv@#x*b\">\n        <field name=\"dertext\">Hello, World!</field>\n      </block>\n    </value>\n  </block>\n  <block type=\"text\" id=\"@Kf$lq//b5g+TgkUQclz\" x=\"10\" y=\"60\">\n    <field name=\"dertext\">I feel great.</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"(7gC*OGG$yxES*=1!Kgd\">println</variable>\n  </variables>\n  <block type=\"funs-h-2-cus\" id=\"3jlNw04eWrV5Facrs8]f\" x=\"11\" y=\"11\">\n    <field name=\"kopf\" id=\"(7gC*OGG$yxES*=1!Kgd\">println</field>\n    <value name=\"args-2\">\n      <block type=\"text\" id=\"NI)yg;:O!Z;@LWv@#x*b\">\n        <field name=\"dertext\">Hello, World!</field>\n      </block>\n    </value>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"(7gC*OGG$yxES*=1!Kgd\">println</variable>\n  </variables>\n  <block type=\"text\" id=\"NI)yg;:O!Z;@LWv@#x*b\" x=\"14\" y=\"16\">\n    <field name=\"dertext\">Hello, World!</field>\n  </block>\n  <block type=\"funs-h-2-cus\" id=\"3jlNw04eWrV5Facrs8]f\" x=\"14\" y=\"55\">\n    <field name=\"kopf\" id=\"(7gC*OGG$yxES*=1!Kgd\">println</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"R0y,B?{B~fcCKDue}^Oz\">str</variable>\n  </variables>\n  <block type=\"funs-h-3-cus\" id=\"A6zB_.9vy%Ybe0,0;r|5\" x=\"19\" y=\"27\">\n    <field name=\"kopf\" id=\"R0y,B?{B~fcCKDue}^Oz\">str</field>\n  </block>\n  <block type=\"text\" id=\"U~rXpfNPb?vO,1UVl+-|\" x=\"19\" y=\"79\">\n    <field name=\"dertext\">Clo</field>\n  </block>\n  <block type=\"text\" id=\"=I%z-d`m$Y!}tUZw}Aa6\" x=\"20\" y=\"126\">\n    <field name=\"dertext\">jure</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"R0y,B?{B~fcCKDue}^Oz\">str</variable>\n  </variables>\n  <block type=\"text\" id=\"=I%z-d`m$Y!}tUZw}Aa6\" x=\"39\" y=\"17\">\n    <field name=\"dertext\">world</field>\n  </block>\n  <block type=\"text\" id=\"SenL*J,`|Bw0#k}|IEEC\" x=\"153\" y=\"26\">\n    <field name=\"dertext\"> </field>\n  </block>\n  <block type=\"funs-h-5-cus\" id=\"7i(NjG.E?wFX|W(orcS_\" x=\"23\" y=\"64\">\n    <field name=\"kopf\" id=\"R0y,B?{B~fcCKDue}^Oz\">str</field>\n  </block>\n  <block type=\"text\" id=\"U~rXpfNPb?vO,1UVl+-|\" x=\"201\" y=\"108\">\n    <field name=\"dertext\">Hello,</field>\n  </block>\n  <block type=\"text\" id=\"LAH+DOnp,`?osXQ^o_|G\" x=\"76\" y=\"122\">\n    <field name=\"dertext\">!</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"R0y,B?{B~fcCKDue}^Oz\">str</variable>\n  </variables>\n  <block type=\"num\" id=\":FV`E?B]gv?gP@,A9y0m\" x=\"21\" y=\"3\">\n    <field name=\"nummer\">1</field>\n  </block>\n  <block type=\"num\" id=\"nX`YC)ztFwAu`8V)6HO$\" x=\"75\" y=\"4\">\n    <field name=\"nummer\">2</field>\n  </block>\n  <block type=\"text\" id=\"SenL*J,`|Bw0#k}|IEEC\" x=\"131\" y=\"5\">\n    <field name=\"dertext\"> </field>\n  </block>\n  <block type=\"text\" id=\"!*}/P;O8_d^+7}3X^V9f\" x=\"211\" y=\"6\">\n    <field name=\"dertext\"> </field>\n  </block>\n  <block type=\"funs-h-6-cus\" id=\"_|g3S5_dZ4X13)EPt(9B\" x=\"14\" y=\"50\">\n    <field name=\"kopf\" id=\"R0y,B?{B~fcCKDue}^Oz\">str</field>\n    <value name=\"args-2\">\n      <block type=\"num\" id=\"5evt!hRjVt)+:9s8X9C[\">\n        <field name=\"nummer\">3</field>\n      </block>\n    </value>\n    <value name=\"args-5\">\n      <block type=\"text\" id=\"sZ]gvuQCk(fE=c|Ny`eS\">\n        <field name=\"dertext\"> </field>\n      </block>\n    </value>\n    <value name=\"args-6\">\n      <block type=\"funs-h-4-cus\" id=\"m!l|[4j-(bCsYcx%_Yjh\">\n        <field name=\"kopf\" id=\"R0y,B?{B~fcCKDue}^Oz\">str</field>\n        <value name=\"args-4\">\n          <block type=\"text\" id=\"U~rXpfNPb?vO,1UVl+-|\">\n            <field name=\"dertext\"> Blast off!</field>\n          </block>\n        </value>\n      </block>\n    </value>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"BXD}Vmyiic{w$!ff0Y-t\">count</variable>\n  </variables>\n  <block type=\"text\" id=\"J+_W2S}A*`LHKS(*]Ti{\" x=\"99\" y=\"49\">\n    <field name=\"dertext\">Hello</field>\n  </block>\n  <block type=\"funs-h-2-cus\" id=\"6cs9U9^U[U5UzIZtj|=}\" x=\"35\" y=\"93\">\n    <field name=\"kopf\" id=\"BXD}Vmyiic{w$!ff0Y-t\">count</field>\n  </block>\n  <block type=\"text\" id=\"$RiOGL7{;[1HFAZ%}l6T\" x=\"151\" y=\"93\">\n    <field name=\"dertext\"/>\n  </block>\n  <block type=\"text\" id=\"Ij;)[(;qH60:w0!trhVp\" x=\"65\" y=\"145\">\n    <field name=\"dertext\">Hello, world</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"9;bQZa1%+|JCx*4hh}!e\">println</variable>\n  </variables>\n  <block type=\"num_sym\" id=\"8G6pUCI_i9Y+:Aq2oNN.\" x=\"43\" y=\"24\">\n    <field name=\"nummer\">false</field>\n  </block>\n  <block type=\"funs-h-2-cus\" id=\"DNR.8BE4(n84O6@.Ovf(\" x=\"2\" y=\"66\">\n    <field name=\"kopf\" id=\"9;bQZa1%+|JCx*4hh}!e\">println</field>\n    <value name=\"args-2\">\n      <block type=\"num_sym\" id=\";GBmZlc=HB:QHR,GTpy@\">\n        <field name=\"nummer\">true</field>\n      </block>\n    </value>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"9;bQZa1%+|JCx*4hh}!e\">println</variable>\n  </variables>\n  <block type=\"funs-h-3-cus\" id=\"(lo?qyTyNo|y:#hae@T^\" x=\"16\" y=\"32\">\n    <field name=\"kopf\" id=\"9;bQZa1%+|JCx*4hh}!e\">println</field>\n    <value name=\"args-2\">\n      <block type=\"text\" id=\"oSn?FbwC::=Blb[-~Eds\">\n        <field name=\"dertext\">Nobody's home:</field>\n      </block>\n    </value>\n  </block>\n  <block type=\"num_sym\" id=\"]6a^CDOU0Pz*Udz|UMB^\" x=\"49\" y=\"90\">\n    <field name=\"nummer\">nil</field>\n  </block>\n</xml>"
   "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n  <variables>\n    <variable id=\"9;bQZa1%+|JCx*4hh}!e\">println</variable>\n  </variables>\n  <block type=\"num_sym\" id=\"]6a^CDOU0Pz*Udz|UMB^\" x=\"128\" y=\"8\">\n    <field name=\"nummer\">nil</field>\n  </block>\n  <block type=\"funs-h-5-cus\" id=\"fE)rQtCTO,{H7;CJ8WB8\" x=\"11\" y=\"45\">\n    <field name=\"kopf\" id=\"9;bQZa1%+|JCx*4hh}!e\">println</field>\n    <value name=\"args-2\">\n      <block type=\"text\" id=\"oSn?FbwC::=Blb[-~Eds\">\n        <field name=\"dertext\">We can print many things:</field>\n      </block>\n    </value>\n  </block>\n  <block type=\"num_sym\" id=\"EkwRHW9YUj50o~,[FO;2\" x=\"56\" y=\"100\">\n    <field name=\"nummer\">true</field>\n  </block>\n  <block type=\"num_sym\" id=\"NA:EgK9CU+aRSkP#[%S0\" x=\"196\" y=\"97\">\n    <field name=\"nummer\">false</field>\n  </block>\n</xml>"
   ])
